frontend/challengebot/challengebot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('web.urls'))

]

frontend/challengebot/web/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from .code_submit import submit_ajax, challenge_ajax
from .accounts import auth_ajax, reg_ajax, log_out
from . import views

app_name = 'web'
urlpatterns = [
    url(r'^games$', views.games, name='games'),
    url(r'^logout$', log_out, name='log out'),
    url(r'^game/(?P<game_id>[0-9]+)$', views.game, name='game'),
    url(r'^jobs$', RedirectView.as_view(url='/jobs/1', permanent=False)),
    url(r'^jobs/(?P<job_page>[0-9]+)$', views.jobs, name='jobs'),
    url(r'^challenges$', views.challenges, name='challenges'),
    url(r'^job/(?P<job_id>[0-9]+)$', views.job, name='job'),
    url(r'^about$', views.about, name='about'),

    url(r'^ranking$', views.ranking, name='ranking'),
    url(r'^ranking/(?P<game_id>[0-9]+)$', views.ranking, name='ranking_redirect'),
    url(r'^ranking/(?P<game_id>[0-9]+)/(?P<rank_page>[0-9]+)$', views.ranking, name='ranking'),
    # AJAX
    url(r'^account/login$', auth_ajax, name='authenticate'),
    url(r'^account/register$', reg_ajax, name='register'),
    url(r'^submit/source/(?P<game_id>[0-9]+)$', submit_ajax, name='submit_source'),
    url(r'^submit/challenge/(?P<source_id>[0-9]+)$', challenge_ajax, name='challenge_source'),
    url(r'^', views.index, name='index'),
]

frontend/challengebot/web/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Game(models.Model):
    memory_limit = models.FloatField()
    time_limit = models.IntegerField()
    name = models.CharField(max_length=50)
    players_min = models.IntegerField(default=2)
    players_max = models.IntegerField(default=2)

    def __str__(self):
        return self.name


class Source(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, null=True)
    path = models.CharField(max_length=260)
    selected = models.BooleanField(default=0)
    LANGUAGE_CHOICES = (
        ('PY', 'Python'),
        ('C', 'C')
    )
    language = models.CharField(choices=LANGUAGE_CHOICES, default='PY', max_length=20)
    RESULT_CHOICES = (
        ('P', 'Pending'),
        ('A', 'Accepted'),
        ('R', 'Rejected'),
        ('D', 'Disqualified'),
    )
    result = models.CharField(max_length=20, choices=RESULT_CHOICES, default='P')

    def get_selected_source(self, game):
        all_sources_set = Source.objects.filter(user=self, game=game)
        for i in range(all_sources_set.count()):
            if all_sources_set[i].selected:
                return all_sources_set[i]
        return None

    def __str__(self):
        return 'Source #' + str(self.id) + " U:" + self.user.username + " G:" + self.game.name


class Job(models.Model):
    STATUS_CHOICES = (
        ('R', 'Registered'),
        ('Q', 'Queued'),
        ('P', 'In progress'),
        ('F', 'Finished')
    )
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Q')
    date = models.DateTimeField('Date of publication')
    game = models.ForeignKey(Game, on_delete=models.CASCADE, default=1)
    log_path = models.CharField(max_length=260, default='')
    author = models.ForeignKey(User, default=0)

    def __str__(self):
        return "Job #" + str(self.id) + " for " + self.game.name + " from " + str(self.date) + ' (' + self.author.username + ')'


class Challenge(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE, default=1)
    challengers = models.ManyToManyField(Source, through='Challenger')

    def __str__(self):
        return "ChallengeJob #" + str(self.job.id) + " for Game " + self.job.game.name


class Challenger(models.Model):
    STATUS_CHOICES = (
        ('W', 'Win'),
        ('T', 'Tie'),
        ('L', 'Lost'),
        ('D', 'Disqualified'),
        ('P', 'Pending')
    )
    challenge = models.ForeignKey(Challenge)
    source = models.ForeignKey(Source)
    status = models.CharField(max_length=15, choices=STATUS_CHOICES, default='P')
    position = models.IntegerField(default=0)
    xp_diff = models.IntegerField(default=0)

    def __str__(self):
        return self.challenge.job.game.name + ' ' + self.source.user.username + ' placed ' + str(self.position) + ' (' + self.status + ')'


class Submission(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    job = models.ForeignKey(Job, on_delete=models.CASCADE, null=True)
    source = models.ForeignKey(Source, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return "Submission of " + self.user.username + " for " + \
               self.job.game.name + " from " + str(self.job.date)


class LevelGame(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    level = models.IntegerField()
    xp_reach = models.IntegerField()
    xp_win = models.IntegerField()
    xp_lost = models.IntegerField()
    xp_draw = models.IntegerField()
    xp_dsq = models.IntegerField()

    def __str__(self):
        return 'Level ' + str(self.level) + ' of game ' + self.game.name


class LevelingUser(models.Model):
    level = models.IntegerField()
    xp = models.IntegerField()
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + ' (' + self.game.name + ' level ' + str(self.level) + ' | xp: ' + str(self.xp) + ')'

frontend/challengebot/web/templates/web/about.html
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'web/style/about.css' %}" />

<div class="big-div">
    <div class="smaller-div" id="smaller-div-1">
        <h3>
            About us
        </h3>
        <p>
            We are a team of 6 students at the Computer Science faculty, Babes-Bolyai University in Cluj-Napoca,
            Romania. This is a project for one of our courses, Software Engineering.
        </p>
    </div>
    <div class="smaller-div" id="smaller-div-2">
        <h3>
            The team
        </h3>
        <ul>
            <li>Neagoș Bianca</li>
            <li>Suciu Irina</li>
            <li>Széll Tamás</li>
            <li>Topan Mihai</li>
            <li>Țelicov Teodora</li>
            <li>Văran Tudor (Team lead)</li>
        </ul>
    </div>
</div>

frontend/challengebot/web/templates/web/challenges.html
<div>
{% if challenges_list %}
    <table>
        <tr>
            <th>#</th>
            <th>Game</th>
            <th>Challengers</th>
            <th>Winner</th>
            <th>Link</th>
        </tr>
        {% for challenge in challenges_list %}
            <tr>
                <td>
                    <p>{{ challenge.id }} </p>
                </td>
                <td>
                    <a href = "/game/{{ challenge.job.game.id }}">{{ challenge.job.game.name }}</a>
                </td>
                <td>
                    <ol>
                        {% for c in challenge.challengers.all %}
                            <li>{{c.user.username}}</li>
                        {% endfor %}
                    </ol>
                </td>
                <td>
                    <b>{{ challenge.winner.user.username }}</b>
                </td>
                <td>
                    <a href="/challenge/{{ challenge.id }}">[v]</a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>No challenges are currently available.</p>
{% endif %}
</div>

frontend/challengebot/web/templates/web/game.html
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'web/style/game.css' %}">

{% load static %}
<script src="{% static 'codemirror2/lib/codemirror.js' %}"></script>

{% load static %}
<script src="{% static 'codemirror2/mode/python/python.js' %}"></script>

{% load static %}
<script src="{% static 'codemirror2/mode/clike/clike.js' %}"></script>

{% load static %}
<link rel="stylesheet" href="{% static 'codemirror2/lib/codemirror.css' %}">

{% load static %}
<link rel="stylesheet" href="{% static 'codemirror2/theme/liquibyte.css' %}">

{% load static %}
<script src="{% static 'web/script/game.js' %}"></script>

{% load static %}
<script src="{% static 'web/script/challenge.js' %}"></script>

{% load mathfilters %}
<div id="game-content">
    <div id="game-data">
        <div class="game-tab">
            <h2>
                Restrictions
            </h2>
            <table class="game-table">
                <tr>
                    <th>
                        <p><b>Name</b></p>
                    </th>
                    <th>
                        <p><b>Memory limit</b></p>
                    </th>
                    <th>
                        <p><b>Time limit</b></p>
                    </th>
                    <th>
                        <p><b>Min. players</b></p>
                    </th>
                    <th>
                        <p><b>Max. players</b></p>
                    </th>
                </tr>
                <tr>
                    <td>
                        <p>
                            {{game.name}}
                        </p>
                    </td>
                    <td>
                        <p>
                            {{game.memory_limit}} Mb
                        </p>
                    </td>
                    <td>
                        <p>
                            {{game.time_limit}} ms
                        </p>
                    </td>
                    <td>
                        <p>
                            {{game.players_min}}
                        </p>
                    </td>
                    <td>
                        <p>
                            {{game.players_max}}
                        </p>
                    </td>
                </tr>
            </table>
        </div>
        <div class="game-tab">
            <h2>
                Requirements
            </h2>
            <div class="game-tab-content">
                {{ game_description }}
            </div>
        </div>
    </div>
    <div id="wrapper-forms">
        {% if request.user.is_authenticated %}
            <div class="game-tab">
                <h2>
                    Submit your bot
                </h2>
                <div class="game-tab-content">
                    <form id="submission-form" action="/submit/source/{{game.id}}" method="post">
                        {% csrf_token %}
                        <input type="hidden" id="game_id" value="{{game.id}}"/>
                        <b>Language:{{form.language}}</b>
                        <textarea name="your_code" id="id_your_code" rows="20" cols="80"></textarea>
                    </form>
                    <div id='submit-error' class='flash-container'></div>
                </div>
                <input type="submit" value="Submit" id="submission-submit"/>
            </div>
            {% if levels %}
                <div class = "game-tab">
                    <h2>
                        Experience distribution
                    </h2>
                    <div class="game-table">
                        <table>
                            <tr>
                                <th>Level</th>
                                <th>XP needed</th>
                                <th>Win</th>
                                <th>Draw</th>
                                <th>Lose</th>
                                <th>Disqualify</th>
                            </tr>
                            {% for level in levels %}
                                <tr>
                                    <td>{{level.level}}</td>
                                    <td>
                                        {% if level.xp_reach == -1 %}
                                            --
                                        {% else %}
                                            {{level.xp_reach}} xp
                                        {% endif %}
                                    </td>
                                    <td>{{level.xp_win}} xp</td>
                                    <td>{{level.xp_draw}} xp</td>
                                    <td>{{level.xp_lost}} xp</td>
                                    <td>{{level.xp_dsq}} xp</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
                {% if leveluser and xp_reach %}
                     <div class="game-tab">
                         <h2>
                             Current standings
                         </h2>
                         <div class="game-tab-content">
                             <div id="player-level"><b>{{leveluser.level}}</b></div>
                             <input id="player-xp" type="hidden" value="{{leveluser.xp}}">
                             <input id="reach-xp" type="hidden" value="{{xp_reach}}">
                             <div id="xp-meter">
                                <div id="xp-gain">

                                </div>
                            </div>
                         </div>
                     </div>
                {% endif %}
            {% endif %}
            {% if p1_source %}
                <div class="game-tab">
                    <h2>
                        Challenge other bots
                    </h2>
                    <form id="challenge-form" action="/submit/challenge/{{p1_source.id}}" method="post">
                        <div class="game-bot-number">
                            {% csrf_token %}
                            {% if game.players_min != game.players_max %}
                            Choose between {{game.players_min|sub:1}} and {{game.players_max|sub:1}} bots
                            {% else %}
                            {% if game.players_min == 2 %}
                            Choose exactly 1 bot
                            {% else %}
                            Choose exactly {{game.players_min|sub:1}} bots
                            {% endif %}
                            {% endif %}
                        </div>
                        <input type="hidden" id="player_source_id" value="{{p1_source.id}}"/>
                        <br>
                        <table class="game-bot-table">
                            <tr>
                                <td rowspan="2">

                                    <div class="challenge-options">
                                        {{ opponents.eligible_opponents }}
                                    </div>

                                </td>
                                <td>
                                    <input type="button" value=">" id="addButton" onclick="add_opponent()"/>
                                </td>
                                <td rowspan="2">
                                    <div class="challenge-options">
                                        {{ opponents.selected_opponents }}
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <input type="button" value="<" id="removeButton" onclick="remove_opponent()"/>
                                </td>
                            </tr>
                        </table>
                        <input type="hidden" id="min_players" value="{{game.players_min}}"/>
                        <input type="hidden" id="max_players" value="{{game.players_max}}"/>
                    </form>
                    <div id='challenge-error' class='flash-container'></div>
                    <input type="submit" value="Challenge" id="challenge-submit"/>
                </div>
            {% endif %}
        {% endif %}
    </div>
</div>

frontend/challengebot/web/templates/web/games.html
{% load static %}
<link rel="stylesheet" type='text/css' href="{% static 'web/style/table.css' %}" />

<div >
    <table>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Min. players</th>
            <th>Max. players</th>
        </tr>

        {% if games_list %}
            {% for game in games_list %}
                <tr>
                    <td>{{game.id}}</td>
                    <td><a href="/game/{{ game.id }}">{{game.name}}</a></td>
                    <td>{{ game.players_min}}</td>
                    <td>{{ game.players_max}}</td>
                </tr>
            {% endfor %}
{% endif %}
    </table>
</div>

frontend/challengebot/web/templates/web/index.html
{% load static %}
    <link rel="stylesheet" type='text/css' href="{% static 'web/style/index.css' %}" />

<div class="questions-wrapper">
    <h2>
        Welcome to Challenge Bot!
    </h2>
    <div class="question-div" id="question-div-1">
        <h3>
            What?
        </h3>
        <p>
            This is a platform for gamers and coders (at the same time) to test their AI skills and game strategies. It
            is the perfect combination between coding and playing. The idea is simple: you read the game rules,
            implement a solution for different game situation, which as whole, make the AI of a game. You submit it and
            then you can challenge other people!
        </p>
    </div>
    <div class="question-div" id="question-div-2">
        <h3>
            How?
        </h3>
        <ul>
            <li>Register using the upper-right button</li>
            <li>Log in</li>
            <li>Choose a game</li>
            <li>Submit your code</li>
            <li>Play with others by challengeing them!</li>
        </ul>
    </div>
</div>
<div class="questions-wrapper">
    <div class="question-div" id="question-div-3">
        <h3>
            What's next?
        </h3>
        <p>
            Our simplest game is <a href="/game/1">Battleships</a>. We recommend you check out that game and submit your
            solution!
        </p>
    </div>
    <div class="question-div" id="question-div-4">
        <h3>
            Supported languages
        </h3>
        <ul>
            We have support for the following:
            <li>Python 2.7</li>
            <li>C++</li>
        </ul>
    </div>
</div>
<div class="questions-wrapper">
    <div class="question-div" id="question-div-5">
        <h3>
            Screenshots
        </h3>
        {% load static %}
        <img src="{% static 'web/style/res/battleships1.png' %}" />
        {% load static %}
        <img src="{% static 'web/style/res/battleships2.png' %}" />
        {% load static %}
        <img src="{% static 'web/style/res/battleships3.png' %}" />
    </div>
</div>

frontend/challengebot/web/templates/web/job.html
        {%load static %}
        <script type="text/javascript" src="{% static 'web/script/screen.js' %}"></script>
        {%load static %}
        <script type="text/javascript" src="{% static 'web/script/jquery-3.2.1.min.js' %}"></script>
        {% load static %}
        <link rel="stylesheet" type='text/css' href="{% static 'web/style/job.css' %}" />
        <div class="wrapper">
                <!--<input type="text" id="winner" value="{{challenge.winner.user.username}}" hidden>-->
                <br>
                <div id="screen">
                    <p id="screen-text">

                    </p>

                    <table id="screen-pixels">

                    </table>
                    <div class="controls">
                        <input class="job-controls" type="button" id="firstButton" value="<<">
                        <input class="job-controls" type="button" id="prevButton" value="<">
                        <input class="job-controls" type="button" id="nextButton" value=">">
                        <input class="job-controls" type="button" id="lastButton" value=">>">
                    </div>
                    <br>
                    <div class="controls">
                        <input class="job-controls" type="button" id="autoButton" value="Play">
                        <input class="job-field" type="text" id="autoInterval" maxlength="4" size="4" value="125">
                        <input class="job-controls" type="button" id="stopButton" value="Stop">
                    </div>
                </div>
                <div id="data" style="display: none;">
                    {% for r in rows %}
                        <p>{{r}}</p>
                    {% endfor %}
                </div>
        </div>

frontend/challengebot/web/templates/web/jobs.html
{% load mathfilters %}
<table id="jobs-table">
    {% load static %}
    <link rel="stylesheet" type='text/css' href="{% static 'web/style/jobs.css' %}" />
    {% load static %}
    <link rel="stylesheet" type='text/css' href="{% static 'web/style/table.css' %}" />
            <tr>
                <th>#</th>
                <th>Status</th>
                <th>User</th>
                <th>Game</th>
                <th>Date</th>
                <th>Participants</th>
                <th>Source(s)</th>
                <th>Result</th>
            </tr>
            {% for job in job_list %}
                <tr>
                    <td>#{{job.id}}</td>
                    <td>{{job.get_status_display}}</td>
                    <td>{{job.author.username}}</td>
                    <td><a href="/game/{{ job.game.id }}">{{job.game.name}}</a></td>
                    <td>{{job.date}}</td>
                    {% for challenge in challenge_list%}
                        {% if challenge.job == job %}
                            <td >
                                {% for source in challenge.challengers.all %}
                                {{source.user.username}}<br>
                                {% endfor %}
                            </td>
                            <td>
                                {% for source in challenge.challengers.all %}
                                {{source.id}}<br>
                                {% endfor %}
                            </td>
                            <td id ="status">
                                {% if challenge.job.status == 'F' %}
                                    <a href="/job/{{ challenge.job.id }}">Results</a>
                                {% else %}
                                    <p id="pending">Pending</p>
                                {% endif %}
                            </td>
                        {% endif %}
                    {% endfor %}
                    {% for sub in submission_list%}
                        {% if sub.job == job %}
                            <td>
                                {{sub.source.user.username}}
                            </td>
                            <td>
                                {{sub.source.id}}
                            </td>
                            <td>
                                {% if sub.job.status == 'F' %}
                                <a href="/job/{{ sub.job.id }}">
                                    {{sub.source.get_result_display}}
                                </a>
                                {% else %}
                                    {{sub.source.get_result_display}}
                                {% endif %}
                            </td >
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
</table>
<div id="jobs-nav">
    <div id="jobs-options">
        {% if job_page != 1 %}
        <a class="jobs-button jobs-button-left" href="/jobs/1">Newest</a>
        {% endif %}

        {% if job_page > 1 %}
        <a class="jobs-button jobs-button-left" href="/jobs/{{ job_page|sub:1 }}">Newer</a>
        {% endif %}

        {% if job_page != max_page %}
        <a class="jobs-button jobs-button-right" href="/jobs/{{ max_page }}">Oldest</a>
        {% endif %}

        {% if job_page < max_page %}
        <a class="jobs-button jobs-button-right" href="/jobs/{{ job_page|add:1 }}">Older</a>
        {% endif %}
    </div>
</div>

frontend/challengebot/web/templates/web/menu.html
<div id="menu">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script>
    {% load static %}
    <link rel="stylesheet" type='text/css' href="{% static 'web/style/menu.css' %}"/>
    {% load static %}
    <link rel="stylesheet" type='text/css' href="{% static 'web/style/flash-service.css' %}"/>
    {% load static %}
    <script type="text/javascript" src="{% static 'web/script/menu.js' %}"></script>
    {% load static %}
    <script type="text/javascript" src="{% static 'web/script/flash-service.js' %}"></script>
    <div id="menuhead">
        <div class="logo-container">
            <a href="/">
                <div id="logo"></div>
                <div id="logo-text"></div>
            </a>
            {%if username %}
            <div class="user-face"></div>
            {% else %}
            <div class="user-face" id="user-face-hiding"></div>
            {% endif %}
        </div>

        <div id="mixer">
            {% load static %}
            <img src="{% static 'web/style/res/sa.png' %}"/>
        </div>
    </div>
    <div class="menu">
        <ul>
            <div id="menu-options">
                <li><a class="left-link" href="/">Home</a></li>
                <li><a class="left-link" href="/games">Games</a></li>
                <li><a class="left-link" href="/jobs">Jobs</a></li>
                <li><a class="left-link" href="/ranking">Ranking</a></li>
                {% if not username %}
                <li><a class="right-link" id="login-prompt">Log in</a></li>
                <li><a class="right-link" id="register-prompt">Register</a></li>
                {% else %}
                <li><a class="right-link" id="user-button" href="/">{{username}}</a></li>
                <li><a class="right-link" id="logout-button" href="/logout">Log out</a></li>

                {% endif %}
                <li><a class="left-link" href="/about">About us</a></li>

            </div>
        </ul>
    </div>
</div>
{% if not username %}
{% load static %}
<script type="text/javascript" src="{% static 'web/script/account.js' %}"></script>
<div id="login-page" class="overlay">
    <a href="javascript:void(0)" class="closebtn" id="close-login-prompt">&times;</a>
    <div class="overlay-content">
        {% load static %}
        <img src="{% static 'web/style/res/user.png' %}">
        <form id='authentication' action='/auth/' method="POST">
            {% csrf_token %}
            <label>Username</label>
            <input class="inputfield" type="text" placeholder="Username" name="username" required>
            <label>Password</label>
            <input class="inputfield" type="password" placeholder="Password" name="password" required>
            <div id='auth-error' class='flash-container'></div>
        </form>
        <input class="inputbutton" type="submit" id="auth-button" value="Login">
    </div>
</div>
<div id="register-page" class="overlay">
    <a href="javascript:void(0)" class="closebtn" id="close-register-prompt">&times;</a>
    <div class="overlay-content">
        {% load static %}
        <img src="{% static 'web/style/res/user.png' %}">
        <form id='registration' action='/new_user/' method="POST">
            {% csrf_token %}
            <label>Username</label>
            <input class="inputfield" type="text" placeholder="Username" name="username" required><br>
            <div id='reg-user-error' class='flash-container'></div>
            <label>E-mail</label>
            <input class="inputfield" type="text" placeholder="E-mail" name="email" required><br>
            <div id='reg-email-error' class='flash-container'></div>
            <label>Password</label>
            <input class="inputfield" type="password" placeholder="Password" name="password" required><br>
            <div id='reg-pass-error' class='flash-container'></div>
            <label>Confirm password</label>
            <input class="inputfield" type="password" placeholder="Password" name="confirm-password" required><br>
            <div id='reg-confirm-error' class='flash-container'></div>
        </form>
        <input class="inputbutton" type="submit" id="reg-button" value="Register">
    </div>
</div>
{% endif %}

frontend/challengebot/web/templates/web/support.html
{% load static %}
    <link rel="stylesheet" type='text/css' href="{% static 'web/style/support.css' %}" />
{% load static %}
    <link rel="stylesheet" type='text/css' href="{% static 'web/style/table.css' %}" />
<div id="table-wrapper">
    <table>
        <tr>
            <th>
                No.
            </th>
            <th>
                Title
            </th>
            <th>
                Type
            </th>
            <th>
                Status
            </th>
            <th>
                Publish date
            </th>
        </tr>
        {% for ticket in ticket_list %}
            <tr>
                <td>
                    {{ticket.id}}
                </td>
                <td>
                    {{ticket.title}}
                </td>
                <td>
                    {{ticket.get_type_display}}
                </td>
                <td>
                    {{ticket.get_status_display}}
                </td>
                <td>
                    {{ticket.date}}
                </td>
            </tr>
        {% endfor %}
    </table>
</div>
<div id="form-wrapper">
    <form action="/ticketsubmit" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" />
    </form>
</div>

frontend/challengebot/web/templates/web/template.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    {% load bootstrap3 %}
    {% bootstrap_css %}
    <meta charset="UTF-8">
    {% load static %}
    <link rel="shortcut icon" href="{% static 'web/style/res/logo_original.png' %}" />
    <title>Challenge Bot</title>
    {% load static %}
    <link rel="stylesheet" type='text/css' href="{% static 'web/style/template.css' %}">
    {%load static %}
    <script type="text/javascript" src="{% static 'web/script/template.js' %}"></script>
    {%load static %}
    <script type="text/javascript" src="{% static 'web/script/jquery-3.2.1.min.js' %}"></script>
</head>
<body>
    <div id="eater"></div>
    {{ menu }}
    <div id="content-wrapper">
        {% for c in content %}
        <div class="content">
            {{ c }}
        </div>
        {% endfor %}
    </div>
</body>
</html>